spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_spring
    username: postgres
    password: test1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  graphql:
    graphiql:
      enabled: true

jwt:
  secret: LPUlAj5LFZEXeedXz1ZnlSCQOLtDemSHHHJFtQCWo0sFjNXUOh92zzqJuHXjREqrcGFFPU
  issuer: technofutur.backend
  expiration: 86400 # 1 day in milliseconds

server:
  port: 8080